# Lecture 6
## Midterm Exam 1 Announcement

### Purpose of this Exam
- This is a "knowledge exam." Its primary purpose is to assess your grasp of the concepts and learning objectives we have discussed in class. It is not designed to trick you or present impossible intellectual challenges.
- I will strictly test you on material that has been taught or demonstrated at least once during our class sessions

### Exam Scope
- The exam covers **Lectures 1 through 6**.
  - *Note: This includes the material covered in today's lecture (Lecture 6).*
- The scope is determined by the "In-Class Lecture Notes" available on Canvas.
- Any concept, function, or syntax that appears in these lecture notes has a possibility to appear on the exam.

### Exam Format
The exam will be 80 minutes in class, consists of two sections:
1. **Short-Answer Questions (7 Total):**
   - These will be a mix of multiple-choice and fill-in-the-blank questions.
2. **Free Response Question (1 Total):**
   - This question will ask you to write code (usually a function).
   - May contain multiple subquestions
   - You will be expected to write code that accepts specific inputs and produces specific outputs under given conditions or constraints.
   - Partial credit will be awarded for the free response question and a selected subset of fill-in-the-blank questions at the instructor's discretion.

### Cheat Sheet Policy
You are allowed to bring **one cheat sheet** to the exam. Please adhere strictly to the following rules:
- **Size:** Standard notebook size (Letter/A4).
- **Sides:** It may be double-sided (front and back).
- **Format:** It must be **100% HAND-WRITTEN**.
  - *Warning:* We will confiscate any cheat sheet that includes printed elements (text, screenshots, or diagrams).
- Start creating this now. The act of writing out your syntax and objectives is a great study process.

### Exam Preparation Strategy & Suggestions
- Go through `Lecture1.ipynb` through `Lecture6.ipynb`. Ensure you understand every lines of code and learning objective discussed.
  - Refer to Detailed Course Notebook for a more in-depth explanation.
  - *Example:* Understand how to use specific functions (e.g., `numpy.arange()`), data types (floating point properties), and structures and algorithms (lists, sorting) etc.
- Be ready for questions of varying depth. An easy question will test a single objective, while a challenging question may combine multiple objectives.
- Please come to office hours if you need clarification on any material in the lecture notes.

### During the Exam
- Read the first page instructions and the specific description of every question before starting.
- Some short-answer questions are easier than others. If you get stuck on a difficult one, do not spend too much time on it—skip it and come back later.
- For the free response question, don't leave it blank. We will give partial credit even on basic code structures.

In [7]:
import numpy as np

In [5]:
a = np.random.randn(10) # randn means I want to generate an array of random numbers instead of just one
b = np.random.randn(10)
c = a<b

In [6]:
print(c)

[False False  True False False  True  True False False False]


I want to output an array so that when a<b I have a\**2 and when a>= b I have b\**2

In [10]:
out = np.zeros(len(a))
out[c] = a[c]**2
not_c = np.logical_not(c) # flip every single boolean value in your c array
out[not_c] = b[not_c]**2
print(out)

[1.14731326e-03 1.36703570e-02 2.85260434e+00 1.02188436e-02
 1.81859647e-01 1.37169977e+00 2.30062839e-01 7.08296004e-03
 1.93164235e-01 4.68980939e-01]


## np.where
find the index of elements in array that satisfies certain condition

In [11]:
in1 = np.array([10,4,-2])
np.where(in1>0)

(array([0, 1]),)

You can use an numpy array of indices to index an numpy array
- [0,2,3] is a python list
- np.array([0,2,3]) turns this into a numpy array
- We can use this new numpy array to index our existing numpy array: a[np.array([0,2,3])]

In [14]:
print(a)
print(a[np.array([0,2,3])])

[ 0.68761567  0.55190637 -1.68896546  0.48861867  0.48811388  1.17119587
 -0.47964866  0.51881572  0.61199808  1.78601473]
[ 0.68761567 -1.68896546  0.48861867]


The good thing is that np.where also provide you an numpy array of indices (that satisfy certain conditions), this means we can use np.where to index numpy array as well

In [15]:
print(in1[np.where(in1>0)])

[10  4]


But this is basically what we did with the boolean array!

In [16]:
flag = in1>0
print(flag)
print(in1[flag])
print(in1[in1>0]) # This line should give me exactly the same thing as the previous cell

[ True  True False]
[10  4]
[10  4]


In [17]:
print(in1[np.where(in1>0)]) # for a more direct comparison
print(in1[in1>0])

[10  4]
[10  4]


Why do we need np.where? Because it can take additional argument that is very useful.
- np.where(condition, out_true, out_false)
- out_true is what you do when the condition returns true
- out_false is what you do when the condition returns false

In [18]:
print(in1)
print(np.where(in1>0,5,-100 ))

[10  4 -2]
[   5    5 -100]


**Revisit this problem**: I want to output an array so that when a<b I have a\**2 and when a>= b I have b\**2

In [19]:
print(np.where(a<b, a**2, b**2))

[1.14731326e-03 1.36703570e-02 2.85260434e+00 1.02188436e-02
 1.81859647e-01 1.37169977e+00 2.30062839e-01 7.08296004e-03
 1.93164235e-01 4.68980939e-01]


[1.14731326e-03 1.36703570e-02 2.85260434e+00 1.02188436e-02
 1.81859647e-01 1.37169977e+00 2.30062839e-01 7.08296004e-03
 1.93164235e-01 4.68980939e-01]

## Additional Numpy Logics Operations
- we just discussed `np.logical_not`
- There are other np.logical operations, for example `np.logical_and` and `np.logical_or`
- `np.logical_or` compare two boolean np array (to generate boolean np array one way is to compare two np arrays)

In [22]:
test1 = np.array([0,5,-10])
test2 = np.array([-1,1,-5])
print(test1<test2)
print(test2>0)
print("np.logical_or",np.logical_or(test1<test2, test2>0))
print("np.logical_and",np.logical_and(test1<test2, test2>0))

[False False  True]
[False  True False]
np.logical_or [False  True  True]
np.logical_and [False False False]


## Using the "Try" command
there will be many times you try to do something but you don't know if it will works. Instead of spitting out an error message, you can simply as python to "ignore" the error.

In [23]:
int("hi")

ValueError: invalid literal for int() with base 10: 'hi'

In [25]:
try:
    int("hi")
except:
    print("oops, something goes wrong")

oops, something goes wrong


In [26]:
data = ["1", "2", "hi", "3"]

In [29]:
def list_to_int(listin):
    out = listin.copy()
    for i in range(len(listin)):
        try:
            int(listin[i])
        except:
            print(f"Convert to integer failed! {listin[i]} cannot be converted into integer")
        else:
            out[i] = int(listin[i])
    return out

In [30]:
list_to_int(data)

Convert to integer failed! hi cannot be converted into integer


[1, 2, 'hi', 3]

This is a very useful functionalities when you work with mixed data types

In [31]:
def keep_ints(listin):
    out = []
    for i in range(len(listin)):
        try:
            out.append(int(listin[i]))
        except:
            print(f"Convert to integer failed! {listin[i]} cannot be converted into integer")
    return out

In [32]:
keep_ints(data)

Convert to integer failed! hi cannot be converted into integer


[1, 2, 3]

You can also append error typ to the except command so that it only captures certay type of error.

In [35]:
def test_error_capture(listin):
    out = []
    for i in range(len(listin)):
        try:
            out.append(int(listin[i]))
        except EOFError:
            print(f"Convert to integer failed! {listin[i]} cannot be converted into integer")
    return out

In [36]:
test_error_capture(data)

ValueError: invalid literal for int() with base 10: 'hi'