# Homework 3
### Wing Huang PID: A18894844
**Date:** 2026-01-27

### Problem 1: logic with numpy

**(a)**


In [10]:
import numpy as np

In [11]:
def square_max (x):
    if not np.iterable(x):
        return x**2

    y = None
    for i in x:
        if y is None or i > y:
            y = i
    return y**2

In [12]:
print(square_max(5))
print(square_max([1,2,3,4,5,6,7,8,9,10]))
print(square_max(np.array([1,114,2,4,2])))

25
100
12996


**(b)**

In [13]:
def shape(a, b, c):
    a = np.asarray(a)
    b = np.asarray(b)
    c = np.asarray(c)

    d = a + b
    e = np.logical_and(d > c, d < 2*(c**2))
    return np.where(e, d, -c)

In [14]:
A1 = np.array([1, 2, 3, 4])
B1 = np.array([1, 1, 1, 1])
C1 = np.array([1, 2, 2, 10])

print(shape(A1, B1, C1))

[ -1   3   4 -10]


In [15]:
A2 = np.array([[0, 2],
               [5, 1]])
B2 = np.array([[3, 1],
               [1, 4]])
C2 = np.array([[2, 1],
               [2, 2]])

print(shape(A2, B2, C2))

[[ 3 -1]
 [ 6  5]]


### Problem 2: Random Numbers

**(a)**

In [16]:
def coin(p):
    r = np.random.rand()
    if r < p:
        return 'Head'
    return 'Tail'

In [17]:
print(coin(0.5))
print(coin(0.7))

Head
Head


In [18]:
for i in range (10):
    print(coin(0.5))

Tail
Tail
Head
Tail
Head
Tail
Tail
Tail
Head
Head


**(b)**

In [46]:
def coin_array(p, n):
    r = np.empty(n)
    for i in range(n):
        if coin(p) == 'Head':
            r[i] = 1
        else:
            r[i] = -1
    return r

In [47]:
print(coin_array(0.5, 10))
print(coin_array(0.7, 10))

[ 1.  1.  1. -1. -1.  1. -1.  1.  1. -1.]
[ 1. -1.  1.  1. -1.  1.  1. -1.  1.  1.]


**(c)**

In [21]:
def game(p):
    m = 50
    flip = 0

    while m > 0 and m < 150:
        if coin(p) == 'Head':
            m += 1
        else:
            m -= 1
        flip += 1

    return flip

In [22]:
for i in range (10):
    print(game(0.45))

248
602
250
778
1080
266
760
474
396
564


In [23]:
for i in range (10):
    print(game(0.5))

1018
3854
2690
6660
19078
4518
1572
2336
2130
5930
